name: chewie_audio
description: An audio player for Flutter with Cupertino and Material play controls
version: 1.5.0
homepage: https://github.com/Sub6Resources/chewie_audio

environment:
  sdk: '>=2.13.0 <4.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  flutter:
    sdk: flutter
  video_player: ^2.4.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/svg/speed.svg

